** positive and negative images generated by Neurogen:

pos-upright, neg-uprught: positive and negative images (each N=50)
pos-inv, neg-inv: positive and negative inverted images (180 degree rotation)

